### ISSUE TITLE
Kaynak Kodu

### ISSUE THREAD

**Issue by ramazansancar** [mzuvin/rekabetAnalizi#1]
Merhaba,
Kaynak kodu var mı?

**Comment by mzuvin** [comment]
Merhaba, kaynak kodu olabilir musait bir zaman da paylasayim ama calisacagindan emin degilim regexler ile yazmistim.

**Comment by mzuvin** [comment]
@ramazansancar kaynak kodu paylaştım dediğim gibi revize ihtiyacı var. py2 ile yazılmış çoğu şey çalışmıyor.

**Comment by ramazansancar** [comment]
> @ramazansancar kaynak kodu paylaştım dediğim gibi revize ihtiyacı var. py2 ile yazılmış çoğu şey çalışmıyor.

Teşekkürler
